name: Send Quiet Hours Reminders
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
jobs:
  send-reminders:
    runs-on: ubuntu-latest
    steps:
      - name: Send Reminders
        run: |
          curl -X POST "${{ secrets.APP_URL }}/api/cron/send-reminders" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json"
